name: modflowapi continuous integration

on:
  schedule:
    - cron: '0 8 * * *' # run at 8 AM UTC (12 am PST)
  push:
    branches:
      - main
      - develop
      - 'release*'
  pull_request:
    branches: [master, develop]

jobs:

  std_setup:
    name: standard installation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash

    steps:

    # check out repo
    - name: Checkout repo
      uses: actions/checkout@v2.3.4

    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Base installation
      run: |
        pip install .

    - name: Print version
      run: |
        python -c "import modflowapi; print(modflowapi.__version__)"


  lint:
    name: linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash

    if: github.event_name != 'schedule'
    steps:
    # check out repo
    - name: Checkout repo
      uses: actions/checkout@v2.3.4

    # Standard python fails on windows without GDAL installation. Using
    # standard python here since only linting on linux.
    # Use standard bash shell with standard python
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Print python version
      run: |
        python --version

    - name: Install Python 3.8 packages
      run: |
        python -m pip install --upgrade pip
        pip install -r etc/requirements.pip.txt

    - name: Run black
      run: |
        echo "if black check fails run"
        echo "  black --line-length 79 ./modflowapi"
        echo "and then commit the changes."
        black --check --line-length 79 ./modflowapi

    - name: Run flake8
      run: |
        flake8 --count --show-source --exit-zero ./modflowapi

    - name: Run pylint
      run: |
        pylint --jobs=2 --errors-only --exit-zero ./modflowapi

